### ISSUE TITLE
TLS proxy error

### ISSUE THREAD

**Issue by CrisRonda** [dadatuputi/bitwarden_gcloud#2]
I have been following your tutorial, (in fact very good and easy to understand) but I am in the middle of an error that I cannot understand because it occurs.
I try to enter my static ip in GCP and this error appears. I have tried creating my own cert and key .pem, which I add in the .env and also in the CaddyFile.
Maybe you know what my mistake might be?
Thank you!
```
f1d0cf4382b1_proxy | 2020/07/29 18:28:50 http: TLS handshake error from XX.XX.XX.XX: no certificate available for '172.18.0.5'
f1d0cf4382b1_proxy | 2020/07/29 18:28:50 http: TLS handshake error from XX.XX.XX.XX: no certificate available for '172.18.0.5'
f1d0cf4382b1_proxy | 2020/07/29 18:28:51 http: TLS handshake error from XX.XX.XX.XX: no certificate available for '172.18.0.5'
f1d0cf4382b1_proxy | 2020/07/29 18:28:51 http: TLS handshake error from XX.XX.XX.XX: no certificate available for '172.18.0.5'
```

**Comment by dadatuputi** [comment]
I also see those error messages, which are because someone is trying to browse directly to your IP address instead of using a domain. I see it from bots/other crawlers that are scanning my IP for http servers but caddy rejects them because it doesn't have a cert for the ip address. 

If you don't have a domain name and instead just want to use the Google cloud ephemeral IP address (or pay for a static IP), you could probably do that but you'll have to read up on the Caddy 2 documentation and edit the Caddyfile to pass self-signed certs to your proxy container. 

Are you using a Cloudflare domain name? If so you can just ignore the proxy errors, which as I said are normal when Caddy sees traffic it can't provide a certificate for.
