### ISSUE TITLE
Firefox addon broken

### ISSUE THREAD

**Issue by mdsupport** [dadatuputi/bitwarden_gcloud#40]
The bitwarden addon for Firefox appears to have been updated. Login box now displays the self-hosted url. Unfortunately, the new version gives invalid username/password error with self-hosted urls but seems to work with standard bitwarden account. MSFT Edge continues to show old design and allows login+sync to the self-hosted server.

Has anyone encounted this situation? Are there any suggestion to debug/fix this? Can the server put in log if the login request was processed by the server?

**Comment by mdsupport** [comment]
Maybe an update is needed based on responses to similar issue raised on [github issue 4257 for official bitwarden repo](https://github.com/bitwarden/clients/issues/4257).

**Comment by dadatuputi** [comment]
Strange - I don't have any issues using my Firefox plugin. Did you have it logged in the Firefox plugin already, and it logged out? Or is this for your first login using the extension? That issue you linked makes it sound like there needed to have been a vaultwarden update since Nov 28. My vaultwarden version according to the Firefox plugin is 1.26.0. Perhaps your vaultwarden needs an update? `docker-compose pull`

**Comment by mdsupport** [comment]
If your addon dialog has not changed then addon has not been updated yet. For me latest version (2022.12.0) released Dec 14, 2022 created the issue.

As a workaround, I rolled back to prior version (2022.10.1 released Oct 19, 2022) to get going.

[This link](https://addons.mozilla.org/firefox/downloads/file/4018008/bitwarden_password_manager-2022.10.1.xpi) will roll back the addon version and keep this lifesaver working.

**Comment by dadatuputi** [comment]
My extension is:

```
Version
2022.12.0
```

and works fine.

What version of vaultwarden are you on?

**Comment by mdsupport** [comment]
How do I find the server version?

**Comment by dadatuputi** [comment]
You can find it in the addon/plugin under Settings -> About. It shows the server is vaultwarden and its version number, at least in the latest version. 

From the google cloud console you can run this command as well: 

```bash
sudo docker exec -it bitwarden ./vaultwarden --version
```

**Comment by mdsupport** [comment]
Feeling bad here. Looks like I never did update docker so it still says `image: bitwardenrs/server:alpine`. Would `docker-compose pull` take care of migration or are there specific steps listed elsewhere?

**Comment by dadatuputi** [comment]
Ah yep that would do it. 

That update was quite a while ago (a0b1c16f6724633f0856da56461b06c3fea3d4a1) but you should just be able to do a `git pull` and get all the changes since you initially did that. Since there have been a bunch of commits since then, I would do something like this (sanity check everything, I make no guarantee this won't break your stuff. Make a backup):

1. `docker-compose down`
1. `git pull`
1. Copy YOUR `.env` to `.env.bak` <- have a backup
1. Copy `.env.template` to `.env` <- this will start you off with a fresh copy of the template
1. Fill out the new `.env` as needed, using values from `.env.bak`
1. `docker-compose up -d`
1. Look at the logs in case anything got messed up: `docker-compose logs -f`

**Comment by mdsupport** [comment]
Shows - `vaultwarden 1.24.0`. So may be image needs to be changed for watchtower to take care of it. Looks like the updates stopped 10 months ago.
