### ISSUE TITLE
[question] warning in watchtower log: falling back to regular pull - Reason: invalid character 'S'

### ISSUE THREAD

**Issue by kurti500** [dadatuputi/bitwarden_gcloud#43]
Hi all,
I get following message in the watchtower logs:

level=warning msg="Could not do a head request for \"containrrr/watchtower:latest\", falling back to regular pull." container=/watchtower image="containrrr/watchtower:latest"
watchtower      | time="2023-01-08T03:00:06+01:00" level=warning msg="Reason: invalid character 'S' looking for beginning of value" container=/watchtower image="containrrr/watchtower:latest"

Any thoughts about the invalid "character 'S' topic? Just found this issue which seems to be resolved since 2020: https://github.com/containrrr/watchtower/issues/715

Nevertheless all containers seem to be scanned OK at the end:
watchtower      | time="2023-01-08T03:00:09+01:00" level=info msg="Session done" Failed=0 Scanned=7 Updated=0 notify=no

Can above warning be avoided somehow or is the regular pull OK as well?

**Comment by dadatuputi** [comment]
It sounds like it was an ephemeral error based on the image repo possibly timing out or showing a server error instead of the JSON object that watchtower or docker was expecting. There's not a lot to go on (I'm making a lot of assumptions, based on https://stackoverflow.com/a/37492750/1486966). If it continues being a problem, and you see that your images aren't updating, we can look a bit further. More logs would help
