### ISSUE TITLE
bug: Timezone doesn't seem to work

### ISSUE THREAD

**Issue by crespire** [dadatuputi/bitwarden_gcloud#46]
I notice that my backup file names and the "new login" timestamps are still in UTC even though I've set the timezone properly (as far as I know). In the `.env` I have set `TZ="America/New_York"` for EST. I've also tried `TZ=America/New_York`

When I go into the shell for the `bitwarden` container, trying `cat /etc/timezone` returns `No such file or directory`. Am I just setting something wrong?

Based on my current config, seems like the `bitwarden` and `proxy` containers don't seem to adhere to my `TZ` setting, but `ddns` and `fail2ban` do:

```bash
user@server ~/bitwarden_gcloud $ docker exec -it bitwarden date
Thu Jan 26 05:39:31 UTC 2023
user@server ~/bitwarden_gcloud $ docker exec -it fail2ban date
Thu Jan 26 00:39:40 EST 2023
user@server ~/bitwarden_gcloud $ docker exec -it ddns date
Thu Jan 26 00:39:47 EST 2023
user@server ~/bitwarden_gcloud $ docker exec -it proxy date
Thu Jan 26 05:39:52 UTC 2023
```

Reading around, would this be the cause? https://github.com/dani-garcia/vaultwarden/issues/574#issuecomment-602255600

**Comment by crespire** [comment]
Reading around, would this be the cause? https://github.com/dani-garcia/vaultwarden/issues/574#issuecomment-602255600

**Comment by crespire** [comment]
Based on my current config, seems like the `bitwarden` and `proxy` containers don't seem to adhere to my `TZ` setting, but `ddns` and `fail2ban` do:

```bash
user@server ~/bitwarden_gcloud $ docker exec -it bitwarden date
Thu Jan 26 05:39:31 UTC 2023
user@server ~/bitwarden_gcloud $ docker exec -it fail2ban date
Thu Jan 26 00:39:40 EST 2023
user@server ~/bitwarden_gcloud $ docker exec -it ddns date
Thu Jan 26 00:39:47 EST 2023
user@server ~/bitwarden_gcloud $ docker exec -it proxy date
Thu Jan 26 05:39:52 UTC 2023
```

**Comment by dadatuputi** [comment]
Hi @crespire 

The `docker-compose.yml` file does not pass the TZ variable to the two containers you mentioned because at the time, neither of them supported setting the timezone (due to being alpine packages). Since then, at least vaultwarden has added the `tzdata` package to their image, so it now works. 

Caddy has explicitly stated that they won't add the package to their proxy alpine image (see [this discussion](https://github.com/caddyserver/caddy-docker/issues/58#issuecomment-643809923), where I piped in back in 2020). I am toying around with just installing the package ad-hoc as part of the compose file, which is what I have done in the past to hack images to do what I want without writing my own dockerfile. I started this project as a way to get more into Docker, and I think if I were to do it again I would just write my own docker files based on existing images. I still think I will re-write the project to do this in the future. 

Anyway, I'll mess around with getting `tzdata` installed in the proxy package and post an update.

**Comment by crespire** [comment]
I'll take a look as well, as I did end up trying to pass `TZ` to
 the bitwarden container already.

**Comment by dadatuputi** [comment]
Check out the changes (do a git pull) and see if that fixes it for you. It worked for me.

**Comment by crespire** [comment]
D'oh! I had made changes to the `docker-compose.yml` but didn't rebuild the images to include the changes. I've pulled and rebuilt and everything works as expected! Thanks!
